function writeVMPperSub(corrval,subnum,settings,params,locations,map) 
% set filename to save 

% write data to file; 
switch params.roisuse
    case 'atlas'
        mapname = sprintf('sub-%d_map-%s_dataAvg-%s_behavMat-%s',...
            subnum,...
            params.roisuse,...
            params.dataAvg,...
            params.behavMatUs); 
        writeVMP_percents(corrval,mapname,settings,params); 
    case 'searchlight'
        mapname = sprintf('sub-%d_map-%s_dataAvg-%s_behavMat-%s',...
            subnum,...
            params.roisuse,...
            params.dataAvg,...
            params.behavMatUs); 
        writeVMP_searchlight(corrval,mapname,locations,map,settings,params); 
end

end