function res = strechMatrix(testedLocations, locations, fmrMatrix)

res = zeros(size(fmrMatrix));
nearest = knnsearch(testedLocations, locations, 'K', 1);
for i = 1 : size(locations, 1);
  res(locations(i, 1), locations(i, 2), locations(i, 3)) = ...
    fmrMatrix(...
      testedLocations(nearest(i),1),...
      testedLocations(nearest(i),2),...
      testedLocations(nearest(i),3));
end
