function reportValuesByROI(sigfdr)
%% this function reports ROI labels for debugging 

load('harvard_atlas_short.mat');
idxreport = find(sigfdr==1); 
for r = 1:length(idxreport)
    fprintf('roi # is %.3d, with %d vxls. ROI is %s\t labels ROI_BY_REGIONS is %s\t\n',...
        idxreport(r),...
        sum(idxreport(r)==labelsdata(:)),...
        ROI{idxreport(r)},...
        ROI_BY_REGIONS{idxreport(r)});
end

for r = 1:size(ROI,2) 
    fprintf('[%0.3d] ROI is %s ROI BY REGIONS is %s vox count is %d\n',...
        r,...
        ROI{r},...
        ROI_BY_REGIONS{r},...
        sum(logical(labelsdata(:)==r)));
end

        
end
